config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about', to: 'homes#about'
  post 'books' => 'books#create'
  resources :books, only: [:new, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :index, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
has_many :books, dependent: :destroy

validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
validates :introduction, length: { maximum: 50 }


def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about] 
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user) # ログインした直後は、ユーザーの詳細ページに遷移
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book_dil = Book.find(params[:id])
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :ima)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    user = User.find(params[:id])
  unless user.id == current_user.id
    redirect_to user_path(current_user.id)
  end

    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user)
  else
    render :edit
  end
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:introduction, :name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>

<table class='table'>
  <tr>
  </tr><%= image_tag user.get_profile_image(100, 100) %>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>
<div class='row'>
  <!-- 編集リンクが未実装 -->
  <%= link_to edit_user_path(user),class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  <!--<a class="btn btn-outline-secondary btn-block" href="users/(id)/edit">-->
  <!--  <i class="fas fa-user-cog"></i>-->
  <!--</a>-->
</div>
<h2 class="mt-3">New book</h2>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
<h1>Editing Book</h1>


  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>

        <%= render 'list', user: current_user %>

        <!-- form_with部分 -->
        <%= form_with model: @book do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>

          <h4>Opinion</h4>
          <%= f.text_area :body %>

          <%= f.submit 'Create Book' %>
        <% end %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <% @books.each do |book| %>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>
            <%= link_to  user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(100, 100) %>
            <% end %>
            </th>
              <th>Title</th>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <th>Opinion</th>
              <td><%= book.body %></td>
              <td><%= link_to "show", book_path(book.id) %></td>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'CreateBooks' %>
<% end %>

app/views/books/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
<%= render 'list', user: @book_dil.user %>



<!-- form_with部分 -->
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>
</div>
      <div class='col-md-8 offset-md-1'>
<div>
  <%= flash[:notice] %>
</div>
<h1>Book detail</h1>
<th>
<%= link_to  user_path(@book_dil.user.id) do %>
<%= image_tag @book_dil.user.get_profile_image(100, 100) %>
<% end %>
</th>

<%= @book_dil.title %>


<%= @book_dil.body %>
<th><%= link_to @book_dil.user.name, user_path(@book_dil.user.id) %></th>


<% if @book_dil.user == current_user %>
<%= link_to "Edit", edit_book_path(@book_dil.id) %>

<%= link_to "Destroy", book_path(@book_dil.id), method: :delete%>

  <% end %>

app/views/homes/about.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>!!
        </h1>
        <p>In
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
             <%= link_to user_path(current_user),class:"nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <a class="nav-link text-light" href="/users">
              <i class="fas fa-users"></i>Users
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/books">
              <i class="fas fa-book-open"></i>Books
            </a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>Log out
            </a>
          </li>
          <% else %>
          <li>
            <%= link_to root_path,class:"nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link"></i>About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/ee0d5227ce.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer'  %>
  </body>
</html>

app/views/users/_list.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>

        <table class='table'>
          <tr><%= image_tag user.get_profile_image(100, 100) %>
          </tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </table>
        <div class='row'>
          <!-- 編集リンクが未実装 -->
          <%= link_to edit_user_path(user),class: 'btn btn-outline-secondary btn-block' do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
          <!--<a class="btn btn-outline-secondary btn-block" href="users/(id)/edit">-->
          <!--  <i class="fas fa-user-cog"></i>-->
          <!--</a>-->
        </div>
        <h2 class="mt-3">New book</h2>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputintroduction", placeholder:"名前"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<%= render 'list', user: @user %>
        
<!-- form_with部分 -->
<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Opinion</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>
<main>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <!-- 投稿した書籍一覧表示を作成しましょう。 -->
        <table class='table table-hover table-inverse'>
          <thead>
            <% @users.each do |user| %>
            <tr>
              <th></th>
              <th>image</th>
              <%= image_tag user.get_profile_image(100, 100) %>
              <th>name</th>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody></tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<%= render 'list', user: @user %>
<!-- form_with部分 -->
<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>
</div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <!-- 投稿した書籍一覧表示を作成しましょう。 -->
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.books.each do |book| %>
            <tr>
              <td>
              <%= link_to user_path(@user) do %>
              <%= image_tag @user.get_profile_image(100, 100) %>
              <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>